FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine

WORKDIR /app

# Copy only csproj first for restore caching
COPY CatalogService/*.csproj ./CatalogService/
RUN dotnet restore ./CatalogService/CatalogService.csproj

# Copy rest of source
COPY CatalogService ./CatalogService

WORKDIR /app/CatalogService

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

# CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]