FROM eclipse-temurin:21-jdk-alpine

# Install Maven
RUN apk add --no-cache maven

# Set working directory inside container
WORKDIR /app

# No need to copy code here; mount it as a volume for live development
