CREATE TABLE `order` (
	id VARCHAR(8) PRIMARY KEY,
	total DECIMAL(10,2),
	placed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	customer_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  CHECK (status != 'CONFIRMED' OR total IS NOT NULL)
);